apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- release.yaml
- repository.yaml

postBuild:
  substitute:
    CAUSELY_VERSION: "v1.0.107-0-gf1ea7ea6bdbd72d1"
  substituteFrom:
    - kind: Secret
      name: causely-secrets