apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- release.yaml
- repository.yaml

postBuild:
  substitute:
    CAUSELY_VERSION: "v1.0.116-0-g200acd7b7a905e78"
  substituteFrom:
    - kind: Secret
      name: causely-secrets