apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- release.yaml
- repository.yaml

postBuild:
  substitute:
    CAUSELY_VERSION: "v1.0.105-0-g2d4556f634881f2a"
  substituteFrom:
    - kind: Secret
      name: causely-secrets