apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: causely
  namespace: causely
spec:
  interval: 1h
  chart:
    spec:
      chart: causely
      version: ${CAUSELY_VERSION}
      sourceRef:
        kind: HelmRepository
        name: causely
        namespace: causely
  values:
    global:
      cluster_name: production

    image:
      tag: ${CAUSELY_VERSION}

    mediator:
      gateway:
        token: ${CAUSELY_TOKEN}
