apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: causely
  namespace: causely
spec:
  interval: 1h
  chart:
    spec:
      chart: causely
      version: v1.0.106-0-gc0dc38f6e3bb3bfa
      sourceRef:
        kind: HelmRepository
        name: causely
        namespace: causely
  values:
    global:
      cluster_name: production

    image:
      tag: v1.0.106-0-gc0dc38f6e3bb3bfa

    mediator:
      gateway:
        token: "ABCSDFGHIJKLMNOPQRSTUVWXYZ"
