apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: causely
spec:
  destination:
    namespace: causely
    server: https://kubernetes.default.svc
  source:
    helm:
      valueFiles:
        - values.yaml
